version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn hello_django.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
      - type: bind
        source: ./mediafiles/
        target: /usr/src/app/mediafiles/  
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/  
    env_file:
      - ./.env
    environment:
        POSTGRES_PASSWORD: ${SQL_PASSWORD}
        POSTGRES_DB: = ${SQL_DATABASE}
        POSTGRES_USER: ${SQL_USER}
        POSTGRES_HOST: ${SQL_HOST}
      
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles/
      - media_volume:/usr/src/app/mediafiles/
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume: